const jerseyArr = [];


jerseyArr['1'] = {'uniform_layers' : 2, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#00611e', 'sc' : '#ffffff', 'stc' : '#00611e', 'mc' : '#ffffff', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '', 'sl5' : '', 'sl6' : '', 'sl7' : '', 'cl2' : '', 'cl3' : '', 'cl4' : '', 'cl5' : '', 'slc' : '', 'slc2' : '', 'slc3' : '', 'slc4' : ''};
jerseyArr['2'] = {'uniform_layers' : 2, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#eb0000', 'cc' : '#eb0000', 'sc' : '#ffffff', 'stc' : '#eb0000', 'mc' : '#ffffff', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['3'] = {'uniform_layers' : 3, 'shoulder_layers' : 1, 'neck_style' : 2, 'clc' : '#FA4616', 'cc' : '#000000', 'sc' : '#000000', 'stc' : '#000000', 'mc' : '#ffffff', 'sl2' : '#FA4616', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['4'] = {'uniform_layers' : 2, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#e3e3e3', 'cc' : '#dde8f1', 'sc' : '#dde8f1', 'stc' : '#070707', 'mc' : '#ff6600', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['5'] = {'uniform_layers' : 3, 'shoulder_layers' : 1, 'neck_style' : 3, 'clc' : '#e3e3e3', 'cc' : '#f9ffff', 'sc' : '#00194d', 'stc' : '#00032c', 'mc' : '#d82000', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['6'] = {'uniform_layers' : 3, 'shoulder_layers' : 1, 'neck_style' : 4, 'clc' : '#ffffff', 'cc' : '#0071cd', 'sc' : '#ffffff', 'stc' : '#0060aa', 'mc' : '#949799', 'sl2' : '#fcf6f2', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['7'] = {'uniform_layers' : 3, 'shoulder_layers' : 1, 'neck_style' : 11, 'clc' : '#00611e', 'cc' : '#fcfcfc', 'sc' : '#ffffff', 'stc' : '#747374', 'mc' : '#ffffff', 'sl2' : '#ef0000', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['8'] = {'uniform_layers' : 3, 'shoulder_layers' : 1, 'neck_style' : 6, 'clc' : '#00611e', 'cc' : '#030202', 'sc' : '#0b0909', 'stc' : '#2e2d2d', 'mc' : '#8a95ac', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['9'] = {'uniform_layers' : 3, 'shoulder_layers' : 1, 'neck_style' : 6, 'clc' : '#00611e', 'cc' : '#FC4C02', 'sc' : '#FC4C02', 'stc' : '#FC4C02', 'mc' : '#115740', 'sl2' : '#D0D0CE', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['10'] = {'uniform_layers' : 2, 'shoulder_layers' : 1, 'neck_style' : 11, 'clc' : '#00611e', 'cc' : '#251b77', 'sc' : '#142296', 'stc' : '#3a359e', 'mc' : '#ffd628', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['11'] = {'uniform_layers' : 3, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#e9db68', 'sc' : '#fff95b', 'stc' : '#9166c6', 'mc' : '#009ab5', 'sl2' : '#fae864', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['12'] = {'uniform_layers' : 5, 'shoulder_layers' : 1, 'neck_style' : 6, 'clc' : '#00611e', 'cc' : '#efefef', 'sc' : '#efefef', 'stc' : '#004da9', 'mc' : '#002c94', 'sl2' : '#bf0004', 'sl3' : '#ffffff', 'sl4' : '#feeb33', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['13'] = {'uniform_layers' : 2, 'shoulder_layers' : 1, 'neck_style' : 6, 'clc' : '#00611e', 'cc' : '#002b8c', 'sc' : '#001784', 'stc' : '#0041ae', 'mc' : '#fdfefe', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['14'] = {'uniform_layers' : 3, 'shoulder_layers' : 1, 'neck_style' : 12, 'clc' : '#000000', 'cc' : '#ff8502', 'sc' : '#000000', 'stc' : '#f4f4f4', 'mc' : '#d80030', 'sl2' : '#000000', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['15'] = {'uniform_layers' : 3, 'shoulder_layers' : 1, 'neck_style' : 5, 'clc' : '#00611e', 'cc' : '#ee5700', 'sc' : '#ff3d00', 'stc' : '#242526', 'mc' : '#fdfefe', 'sl2' : '#ce2700', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['16'] = {'uniform_layers' : 3, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#f10000', 'sc' : '#ff423d', 'stc' : '#fffaf5', 'mc' : '#009dd5', 'sl2' : '#fd0000', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['17'] = {'uniform_layers' : 3, 'shoulder_layers' : 1, 'neck_style' : 4, 'clc' : '#5657f0', 'cc' : '#ff5100', 'sc' : '#ff5100', 'stc' : '#5657f0', 'mc' : '#ffffff', 'sl2' : '#ff5100', 'sl3' : '#5657f0', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['18'] = {'uniform_layers' : 8, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#00611e', 'sc' : '#ffffff', 'stc' : '#00611e', 'mc' : '#ffffff', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'}; // Not
jerseyArr['19'] = {'uniform_layers' : 8, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#00611e', 'sc' : '#ffffff', 'stc' : '#00611e', 'mc' : '#ffffff', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'}; // Not
jerseyArr['20'] = {'uniform_layers' : 3, 'shoulder_layers' : 1, 'neck_style' : 2, 'clc' : '#FE5000', 'cc' : '#020202', 'sc' : '#fdde01', 'stc' : '#020202', 'mc' : '#ffffff', 'sl2' : '#ff460a', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['21'] = {'uniform_layers' : 4, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#2232a6', 'sc' : '#2232a6', 'stc' : '#2232a6', 'mc' : '#5ee045', 'sl2' : '#ffffff', 'sl3' : '#5ee045', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['22'] = {'uniform_layers' : 4, 'shoulder_layers' : 1, 'neck_style' : 5, 'clc' : '#00a859', 'cc' : '#0d0d0d', 'sc' : '#f7f7f7', 'stc' : '#00acf8', 'mc' : '#F7EA48', 'sl2' : '#0d0d0d', 'sl3' : '#6CC24A', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['23'] = {'uniform_layers' : 8, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#00611e', 'sc' : '#ffffff', 'stc' : '#00611e', 'mc' : '#0077ba00', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'}; // Not
jerseyArr['24'] = {'uniform_layers' : 8, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#00611e', 'sc' : '#ffffff', 'stc' : '#00611e', 'mc' : '#ffffff', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'}; // Not
jerseyArr['25'] = {'uniform_layers' : 8, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#00611e', 'sc' : '#ffffff', 'stc' : '#00611e', 'mc' : '#ffffff', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'}; // Not
jerseyArr['26'] = {'uniform_layers' : 4, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#00611e', 'sc' : '#ffffff', 'stc' : '#00611e', 'mc' : '#ffffff', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'}; // Not
jerseyArr['27'] = {'uniform_layers' : 8, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#00611e', 'sc' : '#ffffff', 'stc' : '#00611e', 'mc' : '#ffffff', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'}; // Not
jerseyArr['28'] = {'uniform_layers' : 8, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#00611e', 'sc' : '#ffffff', 'stc' : '#00611e', 'mc' : '#ffffff', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'}; // Not
jerseyArr['29'] = {'uniform_layers' : 8, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#00611e', 'sc' : '#ffffff', 'stc' : '#00611e', 'mc' : '#ffffff', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'}; // Not
jerseyArr['30'] = {'uniform_layers' : 3, 'shoulder_layers' : 1, 'neck_style' : 11, 'clc' : '#00611e', 'cc' : '#d40000', 'sc' : '#d40000', 'stc' : '#d40000', 'mc' : '#6162c8', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['31'] = {'uniform_layers' : 3, 'shoulder_layers' : 1, 'neck_style' : 11, 'clc' : '#00611e', 'cc' : '#eca405', 'sc' : '#eca405', 'stc' : '#eca405', 'mc' : '#00237c', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};
jerseyArr['32'] = {'uniform_layers' : 8, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#00611e', 'sc' : '#ffffff', 'stc' : '#00611e', 'mc' : '#ffffff', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'}; // Not
jerseyArr['33'] = {'uniform_layers' : 8, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#00611e', 'sc' : '#ffffff', 'stc' : '#00611e', 'mc' : '#ffffff', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'}; // Not
jerseyArr['34'] = {'uniform_layers' : 8, 'shoulder_layers' : 1, 'neck_style' : 1, 'clc' : '#00611e', 'cc' : '#00611e', 'sc' : '#ffffff', 'stc' : '#00611e', 'mc' : '#ffffff', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'}; // Not
jerseyArr['35'] = {'uniform_layers' : 2, 'shoulder_layers' : 1, 'neck_style' : 2, 'clc' : '#2d2a2b', 'cc' : '#2d2a2b', 'sc' : '#2d2a2b', 'stc' : '#2d2a2b', 'mc' : '#d81e9b', 'sl2' : '#ffffff', 'sl3' : '#ffffff', 'sl4' : '#ffffff', 'sl5' : '#ffffff', 'sl6' : '#ffffff', 'sl7' : '#ffffff', 'cl2' : '#ffffff', 'cl3' : '#ffffff', 'cl4' : '#ffffff', 'cl5' : '#ffffff', 'slc' : '#ffffff', 'slc2' : '#ffffff', 'slc3' : '#ffffff', 'slc4' : '#ffffff'};


export default jerseyArr;